name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install eggs cli
        run: deno install -Af --unstable https://x.nest.land/eggs@0.3.9/eggs.ts

      - name: Setup eggs cli
        env:
          EGGS_TOKEN: ${{secrets.EGGS_TOKEN}}
        run: eggs link "$EGGS_TOKEN"

      - name: Publish
        run: eggs publish --version $RELEASE_VERSION
